name: car_driver_alert_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & platform integrations
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_secure_storage: ^9.0.0
  google_mlkit_face_detection: ^0.7.0

  # Charts
  syncfusion_flutter_charts: ^30.1.40

  # Camera preview + capture
  camera: 0.11.2

  # Optional: handle runtime permissions
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
